# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  enabled: false

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'MSBuild'
    projectKey: 'Demo'
    projectName: 'Demo'
    extraProperties: |
      sonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml
      sonar.cs.vstest.reportsPaths=**\TestResults\*.trx

- task: InlinePowershell@1
  inputs:
    Script: 'dotnet restore'

- task: DotNetCoreCLI@2
  displayName: .Net Build
  inputs:
    command: 'build'
    projects: '**\*.sln'
    arguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
  enabled: false

- task: VSBuild@1
  displayName: VS Build
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: .Net Test
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect:"Code Coverage"'

- task: VSTest@2
  displayName: VS Test
  inputs:
    testSelector: 'testAssemblies'
    codeCoverageEnabled: true
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    resultsFolder: '$(Common.TestResultsDirectory)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    publishRunAttachments: true

- task: SonarQubeAnalyze@4

- task: sonar-buildbreaker@8
  inputs:
    SonarQube: 'sonar'
  enabled: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
